# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='herbiscide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=128)),
                ('genus', models.CharField(max_length=128)),
                ('organism', models.TextField()),
                ('genbankId', models.TextField()),
                ('description', models.TextField()),
                ('submissionDate', models.TextField()),
                ('seqTechnology', models.TextField()),
                ('taxonomy', models.TextField()),
                ('sequence', models.TextField()),
                ('sequenceLength', models.TextField()),
                ('authors', models.TextField()),
                ('comment', models.TextField()),
                ('consrtm', models.TextField()),
                ('journal', models.TextField()),
                ('location', models.TextField()),
                ('medline_id', models.TextField()),
                ('pubmed_id', models.TextField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'herbiscide',
                'managed': False,
            },
        ),
    ]
